language: scala
scala:
  - 2.9.3
  - 2.10.6
  - 2.11.11
  - 2.12.2
script:
  - sbt -jvm-opts travis/jvmopts.compile ... compile
  - sbt -jvm-opts travis/jvmopts.test ... test
sbt_args: -no-colors -J-Xss2m

